// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-s8j337SOX0GRNh1bUOgV7iaeYnRV_E',
    appId: '1:337076486270:web:2c7243448f0c1625fe982f',
    messagingSenderId: '337076486270',
    projectId: 'flutterfire-3bdbd',
    authDomain: 'flutterfire-3bdbd.firebaseapp.com',
    storageBucket: 'flutterfire-3bdbd.appspot.com',
    measurementId: 'G-56KBH0742Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApxDXV4m0zWuWWzifQAI-I-3OFoGHJMBE',
    appId: '1:337076486270:android:fc134df4547ad3b1fe982f',
    messagingSenderId: '337076486270',
    projectId: 'flutterfire-3bdbd',
    storageBucket: 'flutterfire-3bdbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiO5Eb89ImYUIAS7Pfi8Gn9SmSDtViUGY',
    appId: '1:337076486270:ios:c2daecf3baefcd8ffe982f',
    messagingSenderId: '337076486270',
    projectId: 'flutterfire-3bdbd',
    storageBucket: 'flutterfire-3bdbd.appspot.com',
    iosClientId: '337076486270-t8698vqthgbkc0vdeuderp5hl609d195.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiO5Eb89ImYUIAS7Pfi8Gn9SmSDtViUGY',
    appId: '1:337076486270:ios:c2daecf3baefcd8ffe982f',
    messagingSenderId: '337076486270',
    projectId: 'flutterfire-3bdbd',
    storageBucket: 'flutterfire-3bdbd.appspot.com',
    iosClientId: '337076486270-t8698vqthgbkc0vdeuderp5hl609d195.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
